/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>

#include "interface.h"
#include "support.h"

extern char FIFO_FILE_NAME[256];

int
main (int argc, char *argv[])
{
  GtkWidget *window1;
  int r;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  if ( argc < 2) 
   {
       perror("no --fifo=/...  option given\nexit\n");
       return 1;
   }

  //programm option handling
  for (r=1; r<argc; r++)
  {

       // directory from the *.bm metapackage files
       if ( strncmp( argv[r], "--fifo=/", 8 )  == 0 ) {
            strncpy(FIFO_FILE_NAME, argv[r], 256);
       }

  }


  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window1 = create_install_progressbar ();
  gtk_widget_show (window1);

  gtk_main ();
  return 0;
}

